coreos/coreos-ci

HACKING.md, README.md, jenkins/config/github-coreosbot.yaml, jenkins/config/github-oauth.yaml, jenkins/config/github-webhook.yaml, jenkins/config/seed.yaml, jobs/seed-github-ci.Jenkinsfile, manifests/jenkins.yaml, manifests/jenkins.yaml.orig
This commit includes all the juicy bits needed to set up a Jenkins
instance in which to run our upstream CI. Lots going on here, but some
highlights:
- the configs are fully declarative; there's nothing more to set up once
Jenkins is up (well, almost... working on that)
- we use the same Jenkins build config as the FCOS pipeline to match its
environment
- we set up GitHub OAuth for authentication
- the job creation system is kept flexible enough that it's not *just*
for running GitHub PR tests, any arbitrary job can be added; one
simply needs to add the Jenkinsfile to `jobs/` (in fact, I'd like to
experiment with the same setup for the FCOS pipeline itself)
Anyway, there's more tweaks needed to get this where we want, but I
think it's in a good enough state to get it in.
=> tree: import manifests, configs, and jobs

jobs/seed-github-ci.Jenkinsfile
Before trying to migrate repos already hooked up to projectatomic-ci,
let's start with a repo which doesn't currently have any PR testing set
up to make sure everything works.
Requires: https://github.com/jlebon/coreos-ci/pull/1
=> jobs: enroll coreos/ignition-dracut

jenkins/config/coreos-ci-lib.yaml
As mentioned here:
https://github.com/coreos/coreos-ci-lib/pull/10#issuecomment-586016504
we're currently using the `coreos-ci` branch for the new repos hooked up
to CoreOS CI so as to not have breaking changes to master affect
previously hooked up repos.
=> coreos-ci-lib: default to coreos-ci branch

jobs/seed-github-ci.Jenkinsfile
Let's migrate repos over to the new project, starting with the most
popular one.
=> jobs: migrate coreos/coreos-assembler

jobs/seed-github-ci.Jenkinsfile
These ones should be be pretty easy to migrate.
Works on top of https://github.com/coreos/coreos-ci/pull/5.
=> jobs: migrate coreos/fedora-coreos-*

jobs/seed-github-ci.Jenkinsfile
Final one to migrate!
Then we can start enrolling other repos that still need some CI.
=> jobs: migrate ostreedev/ostree

jenkins/config/github-oauth.yaml
I don't quite remember why I had added `repo` there... I don't think we
need this, so let's just drop it and see if something breaks.
Fixes: #12
=> config: drop repo scope from oauth config

jenkins/config/coreos-ci-lib.yaml
We can go back to using master on this now.
=> config: use master branch of coreos-ci-lib

HACKING.md, manifests/jenkins.yaml, manifests/jenkins.yaml.orig
```
commit 2935555c05843d3ff72302425016fe46b375cec5
Date:   Thu Jul 9 13:41:18 2020 -0400
HACKING.md: update for OCP4
A bunch of things changed in the OCP UX from OCP3. Notably the CLI for
creating secrets.
Also fix missing `JENKINS_JOBS_URL` override needed when defining the
Jenkins S2I.
commit 403903a501386367b7a47876ecc6eee3d2097d70
Date:   Thu Jul 9 13:42:18 2020 -0400
manifests: update to latest jenkins-persistent template
Rebase our Jenkins template on top of the latest OCP4 one, and move from
jenkins-ephemeral to jenkins-persistent. In the end, it's simply not
sustainable to retrigger tests for all open PRs in all the repos every
time our pod is restarted or there's a new rollout.
```
=> Updates for OCP4 migration

jobs/seed-github-ci.Jenkinsfile
We're hitting an issue in rpm-ostree where Jenkins' `git merge` is
failing because of unmerged files:
https://github.com/coreos/rpm-ostree/pull/2206
Reading https://issues.jenkins-ci.org/browse/JENKINS-44598, this may be
due to re-using the same workspace and accumulating state there,
combined with possibly bugs in the git plugin itself. (Note this is
different from the workspace in which builds happen; this one lives on
the master and is just used for fetching).
Let's just always nuke the workspace.
=> jobs/seed-github-ci: nuke workspace for each job

jobs/seed-github-ci.Jenkinsfile
Otherwise we blow away the git repo which Jenkins uses to know whether
something changed, and so we end up rebuilding all the PRs and branches
every time a branch index refresh happens (currently scheduled for once
a day).
This essentially reverts #18. The original PR which prompted this is
merged now. Let's keep an eye on the upstream issue.
=> jobs/seed-github-ci: stop wiping workspace

HACKING.md, jenkins/config/kubernetes-cap.yaml, jobs/seed-github-ci.Jenkinsfile
```
commit e15325f8d609399cbfa98301a4828433fef868c7
Date:   Tue Dec 15 20:21:38 2020 -0500
HACKING.md: fix path to jenkins-s2i.yaml build
commit 295bdffb2ac54c3ec949155bb7410f62f6f24154
Date:   Tue Dec 15 17:37:48 2020 -0500
jenkins/config: cap max number of pods to 15
This ensures that we never tax the cluster too hard, which seems to have
repercussions on other projects like the Fedora CoreOS pipeline.
Went with 15 for now, we can see how it goes and adapt it up or down in
the future.
commit 69a720fd0b52ffc95a25e09746c48aa68f0ea716
Date:   Wed Dec 16 10:50:28 2020 -0500
github-ci: don't rebuild all PRs when base branch changes
Otherwise, we'll be spamming the cluster too much each time a PR merges.
This obviously exposes us to "semantic conflicts" (see …
```
=> Various improvements to make CoreOS CI less greedy

jenkins/config/github-webhook.yaml, jenkins/config/timestamper.yaml
Follow-up to coreos/fedora-coreos-pipeline#309.
=> jenkins/config: turn on timestamper for all pipeline jobs

HACKING.md
We're trying to use a coreosbot token which doesn't have `git push`
access since CoreOS CI doesn't strictly need it.
=> HACKING: clarify coreosbot token type

jenkins/config/kubernetes-cap.yaml, jobs/seed-github-ci.Jenkinsfile
```
commit 7adecf5108c5a2803f0b824c5fe1ff7e733f6102
Author: Jonathan Lebon <jonathan@jlebon.com>
Date:   Thu Apr 8 09:57:10 2021 -0400
jobs/seed-github-ci: don't periodically scan branches
Because we don't have persistent storage, everytime Jenkins gets
reprovisioned, it wants to test ancient PRs when it does its first
scheduled repo scan. This unnecessarily bogs down the cluster and
increases the flakiness of test runs we actually care about.
So tell Jenkins to stop doing that.
The downside here is that Jenkins doesn't get to GC deleted
PRs/branches, but meh... the whole pod gets periodically wiped anyway.
```
```
commit ac366c06a7e85fa51431a8c1069d30c54001ee85
Author: Jonathan Lebon <jonathan@jlebon.com>
Date:   Thu Apr 8 10:06:44 2021 -0400
jenkins/config: cap concurrent pods to 6
Our …
```
=> Don't periodically scan branches and cap concurrent pods to 6

manifests/jenkins.yaml
```
commit f09d9d8710152044738d3db2aecb44ac28331caa
Author: Jonathan Lebon <jonathan@jlebon.com>
Date:   Thu Apr 8 12:04:31 2021 -0400
jenkins: increase HEARTBEAT_CHECK_INTERVAL to 10 mins
The durable-task-plugin sometimes errors with "process apparently never
started" if the cluster is under heavy load because the script hasn't
had a chance to start yet. The default timeout is 5 mins, but let's try
to bump that to 10 mins to see if it helps. It may be that the problem
is elsewhere, in which case we can revert this.
Closes: #28 (hopefully)
```
```
commit d368b0da122955d18c21de9109ba1ade62914f5f
Author: Jonathan Lebon <jonathan@jlebon.com>
Date:   Thu Apr 8 12:08:24 2021 -0400
jenkins: turn on LAUNCH_DIAGNOSTICS for durable-task-plugin
Let's follow what the helper message says and turn …
```
=> jenkins: increase HEARTBEAT_CHECK_INTERVAL to 10 mins and turn on LAUNCH_DIAGNOSTICS

HACKING.md, manifests/jenkins.yaml, manifests/pvc.yaml
After discussions with the CentOS CI folks, I was pointed to an
alternative to the NFS PVC. We can use a "local PVC" which is tied to a
specific node.
This does mean that Jenkins itself will be pinned to that node (but
anyway, all the heavy work is done in separate unconstrained pods) and
that we'll lose all the data if a hardware failure happens (there's no
redundancy/backups like NFS).
This is fine for upstream CI though and is much better than what we
currently have.
=> Move to local PVC

jenkins/config/kubernetes-plugin.yaml
There is a bug in the Jenkins OpenShift image which causes the
Kubernetes credential that it was supposed to create not to happen if
there are JCASC dropins which also create credentials, like we do here.
The symptom is:
org.jenkinsci.plugins.kubernetes.auth.KubernetesAuthException: No
credentials found with id 1a12dfa4-7fc5-47a7-aa17-cc56572a41c7
Use the documented workaround to fix this.
See: https://bugzilla.redhat.com/show_bug.cgi?id=1956652
See: https://access.redhat.com/solutions/6016001
=> jenkins/config: workaround jcasc bug in openshift/jenkins

jenkins/config/seed.yaml
The call interface changed to just take one argument.
See https://github.com/coreos/fedora-coreos-pipeline/commit/13b9d25700dfc29f30f02ab4d614eaad99c6b0e0
=> seed: fix call to get_annotation

manifests/jenkins.yaml
The default is 30 minutes, which is short enough that you sometimes have
to log back in multiple times a day. Let's just bump it to one day.
Same as https://github.com/coreos/fedora-coreos-pipeline/pull/456.
=> manifests/jenkins: bump session timeout

jobs/seed-github-ci.Jenkinsfile
There's a bug in BlueOcean where a link to a job containing slashes will
not work:
https://issues.jenkins.io/browse/JENKINS-47604
Let's hack around this by not creating folders and just having the jobs
live at the top-level.
=> jobs: don't create jobs in folders

jobs/seed-github-ci.Jenkinsfile
That repo doesn't use CoreOS CI at all, so just delete it.
=> jobs: drop butane

README-upstream-ci.md
The `coreos-ci` branch is outdated (and will soon be deleted). Fix the
links to use `main`.
Reported-by: Luca BRUNO <luca.bruno@coreos.com>
=> README-upstream-ci.md: fix links to coreos-ci-lib

README-upstream-ci.md
We hit this recently. Let's write this stuff down so it's easier to know
in the future what needs to be done.
=> README-upstream-ci: document contributor trust

manifests/jenkins.yaml
Jenkins stores configs and plugins in a single directory, which is on a
PVC mount. When updating the Jenkins image, by default new plugins in
the image are not copied over into the PVC. If we want to make the image
plugins authoritative (i.e. if we actually want plugin updates), we need
to opt into it via an env var.
=> manifests/jenkins: enable OVERRIDE_PV_PLUGINS_WITH_IMAGE_PLUGINS

manifests/jenkins.yaml
This matches what we did in the FCOS pipeline:
https://github.com/coreos/fedora-coreos-pipeline/pull/671
The bits from that PR to actually set up the imagestream, we will already inherit here.
=> manifests/jenkins: override default jenkins-agent image

HACKING.md
We no longer have a cosa imagestream, and the Jenkins BuildConfig is now called `jenkins-s2i`.
Noticed these while updating CoreOS CI today.
=> HACKING.md: minor tweaks

jobs/bodhi-trigger.Jenkinsfile, jobs/test-override.Jenkinsfile
This job is a step towards better integrating our CI into the rest of
Fedora QA.
The job triggers on Fedora messages from Bodhi whenever an update is
created or edited. It then resolves the Bodhi update to a relevant FCOS
stream, and trigger the `test-override` job with the right parameters.
The implementation details here are a bit messy. Triggering on "a new
Bodhi update" isn't as simple as I would've liked and mapping back to
streams is a bit hairy, but it works!
There's of course a lot of cleanups we could do here (many are marked
in the code), though I'm hoping we can get this in to gain some early
experience and work on cleanups in parallel with the larger task of
adding reporting and socializing it.
See also: https://github.com/coreos/fedora-coreos-tracker/issues/17
=> jobs: add `bodhi-trigger` job

HACKING.md, jobs/bodhi-trigger.Jenkinsfile, jobs/test-override.Jenkinsfile
Call out to the new `resultsdb-report` script in cosa to report test
results back to ResultsDB. Report when first running and then again with
final test results.
Just this alone seems sufficient for the results to show up in Bodhi's
"Automated Tests" tab.
With this, we'll then be able to work on adding policies in Greenwave.
=> jobs/bodhi-trigger: add reporting to ResultsDB

jenkins/config/jms.yaml
This configures the JMS messaging plugin to connect to the public endpoint of the Fedora messaging bus.
The tricky thing is passing in the keystores. The plugin does not support using Jenkins credentials[[1]] so we can't leverage kubernetes-credentials-provider.
We could do it the old way, which is to mount the secret into the Jenkins pod, but since d6d1f61, CoreOS CI now uses the exact same `jenkins.yaml` manifest as the production pipeline and we don't want to bind mount it there.
Instead, we hack around this by just baking the keystores in the Jenkins image at `$JENKINS_HOME/jms-messaging-stores`.
[1]: https://github.com/jenkinsci/jms-messaging-plugin/issues/263
=> jenkins/config: add JCASC dropin for jms-messaging-plugin

jobs/bodhi-trigger.Jenkinsfile
When propagating the result of test-override back to bodhi-trigger, we were trying to read from the `test` variable where it was out of scope.
Move it within its scope.
=> jobs/bodhi-trigger: fix result propagation

bodhi-testing.yaml
The test pattern for `toolbox` was incorrect and so didn't match anything.
For that component and some others, instead of specifying a full test path, make the patterns more globby. That makes them more obviously right, and resistant to the tests moving.
Fixes 6c1f869 ("bodhi-testing.yaml: support specifying tests to run").
=> bodhi-testing.yaml: make test patterns more globby

jobs/seed-github-ci.Jenkinsfile
The Prow CI we have in those repos are extremely slow and annoying to maintain. We're still going to need it for now to at least build RHCOS with actual RHEL RPMs, but at least for CentOS Stream we should be able to build that fine in CoreOS CI. (We don't have access to the OCP RPMs, but with https://github.com/openshift/os/issues/799, we'll move those out of the base compose anyway.)
=> jobs/seed-github-ci: add openshift/os

jobs/bodhi-trigger.Jenkinsfile
When a snoozed test expires, if it has the `warn: true` key on, we'll start warning and that'll show up as an UNSTABLE build. These warnings are more for test maintainers than for public consumption so don't translate them to NEEDS_INSPECTION because that will block updates on gated components.
=> jobs/bodhi-trigger: report SUCCESS even for UNSTABLE builds

jobs/bodhi-trigger.Jenkinsfile
If a test pattern is marked as `skip`, then respect that. Don't force `basic` to run in that case. The logic there was meant as a way to force `basic` to always run *if* some other tests were also selected, not to counteract `skip`.
Fixes 6c1f869 ("bodhi-testing.yaml: support specifying tests to run").
=> jobs/bodhi-trigger: respect `test-patterns: skip`

jobs/test-override.Jenkinsfile
Otherwise, if the override we're testing is pulling in new dependencies, we won't know to fetch them. This came up in https://bodhi.fedoraproject.org/updates/FEDORA-2024-969f546f80 which is adding a dep on `composefs`.
This also matches CI in the coreos/fedora-coreos-config repo.
(Aside: we've talked in the past about getting notified when new deps are added and the previous behaviour coincidentally did that, but this doesn't seem like the right place for it; we shouldn't block packages from entering Fedora on that account. That check probably belongs in `bump-lockfile` instead).
=> jobs/test-override: run `cosa fetch` with `--with-cosa-overrides`

HACKING.md, jobs/bodhi-trigger.Jenkinsfile
This job is still relatively new. Push out failure notifications to Matrix to increase visibility and make it easier to collaborate on investigating issues.
=> jobs/bodhi-trigger: send failure notifications to Matrix

HACKING.md
change already done in the cluster
=> hacking: fix matrix webhook_url env var name

jobs/bodhi-trigger.Jenkinsfile
Sometimes, Bodhi testing is broken for a few days if rawhide is in a bad shape. Let's also have the test report successes so that it's easier to tell when upstream testing have been fixed. It makes it more obvious also when e.g. just a single run failed in a series of otherwise passing runs.
=> jobs/bodhi-trigger: also report test successes

jobs/bodhi-trigger.Jenkinsfile
That makes it easier to copy/paste if we want to replay a job (currently even replaying a fedmsg-triggered job will still ask you to input the `CI_MESSAGE`).
=> jobs/bodhi-trigger: print raw JSON instead of parsed object

bodhi-testing.yaml
We need to also tests theses, as we need them to support kdump. This would have caught https://github.com/coreos/fedora-coreos-tracker/issues/1813
=> bodhi-testing: add kexec-tools and makedumpfile

jobs/test-override.Jenkinsfile
This matches what we do in the pipeline.
Motivated by wanting to get to the bottom of
https://github.com/coreos/fedora-coreos-tracker/issues/1796, which happens often in the Bodhi tests.
=> jobs/test-override: respect env vars for stream

jenkins/config/github-oauth.yaml
Ideally these ACLs would be finer-grained still so that each org members can only affect jobs related to their orgs. But OTOH cancelling and retriggering tests doesn't have to be a super privileged action anyway.
=> jenkins/config: allow rhkdump org members to cancel and retrigger runs

bodhi-testing.yaml
As it was it would try to run `cosa kola run fcos.upgrade.basic basic` which would throw an error since the upgrade test needs to be run through `cosa kola run-upgrade`.
=> bodhi-testing: fix zincati configuration

jobs/bodhi-trigger.Jenkinsfile, jobs/test-override.Jenkinsfile
This way one can easily replay ↺ a job to retry a failed test and still have the results reported back to Bodhi.
Should resolve https://github.com/coreos/coreos-ci/issues/64
=> lower resultsdb reporting into test-override job

jobs/bodhi-trigger.Jenkinsfile
It's boolean, not a string param.
=> jobs/bodhi-trigger: fix type of param based to test-override

jobs/test-override.Jenkinsfile
It's used in the finally so we need it at a higher scope.
=> test-override: increase scope of blueocean_url var

jobs/test-override.Jenkinsfile
We had a recent job timeout because it went over 150. Absent of us trimming tests, let's bump it for now.
=> jobs/test-override: bump timeout to 200m

bodhi-testing.yaml
This means failures will cause GRUB2 to not flow directly into rawhide. It gives us time to investigate any issues.
=> bodhi-testing: gate grub2 on CoreOS tests

jobs/test-override.Jenkinsfile
This was done in [1] so we much update the function call here.
[1] https://github.com/coreos/fedora-coreos-pipeline/commit/b143caad35d9922ea3ecd4617e728a58947616bc
=> test-override: use new get_source_config_for_stream()

jobs/test-override.Jenkinsfile
We're still ironing out issues, but we don't want to cause confusion with Bodhi users. So for now just keep using the legacy path.
=> jobs/test-override: disable buildah path for now

jobs/test-override.Jenkinsfile
The .config-gitrev is legacy. Let's update to use the newer API.
xref: https://github.com/coreos/coreos-assembler/pull/4282
=> jobs/test-override: use newer API for coreos config git rev
